---
nmcli_connections:
  - conn_name: System eth0
    ifname: eth0
    gw4_ignore_auto: true
  - conn_name: central-office2
    ifname: eth1
    ip4: '192.168.255.6/30'
    gw4: '192.168.255.5'
  - conn_name: office2-dev
    ifname: eth2
    ip4: '192.168.1.1/25'
  - conn_name: office2-test
    ifname: eth3
    ip4: '192.168.1.129/26'
  - conn_name: office2-hardware
    ifname: eth4
    ip4: '192.168.1.193/26'
